Enable for general linux

diff --git a/change-gdm-background b/change-gdm-background
--- a/change-gdm-background
+++ b/change-gdm-background
@@ -10,51 +10,28 @@ if [ "$(id -u)" -ne 0 ] ; then
     exit 1
 fi
 
-# Check what linux distro is being used.
-distro="$(lsb_release -c | cut -f 2)"
-if ! [[ "$distro" =~ (focal|groovy|hirsute) ]]; then
-    echo 'Sorry, this script only works with focal, groovy or hirsute distros.'
-    exit 1
-fi
-
 # Check if glib 2.0 development libraries are installed.
 if [ ! -x "$(command -v glib-compile-resources)" ]; then
     echo 'Additional glib 2.0 libraries need to be installed.'
-    read -p 'Type y or Y to proceed. Any other key to exit: ' -n 1
-    if [[ "$REPLY" =~ ^[yY]$ ]]; then
-	apt install libglib2.0-dev-bin
-    else
-	echo "This tool can't run without required libraries"
-	echo "Exiting."
-	echo
-	exit 1
-    fi
+    echo "This tool can't run without required libraries"
+    echo "Exiting."
+    echo
+    exit 1
 fi
 
 # Assign the default gdm theme file path.
-if [ "$(lsb_release -i | awk '{print $3}')" == 'Ubuntu' ]; then
-    gdm3Resource=/usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource
-elif [ "$(lsb_release -i | awk '{print $3}')" == 'Pop' ]; then
-    gdm3Resource=/usr/share/gnome-shell/theme/Pop/gnome-shell-theme.gresource
-fi
+gdm3Resource=/usr/share/gnome-shell/gnome-shell-theme.gresource
 
 # Create a backup file of the original theme if there isn't one.
-[ ! -f "$gdm3Resource"~ ] && cp "$gdm3Resource" "$gdm3Resource~"
+[ ! -f "$gdm3Resource.ori" ] && cp "$gdm3Resource" "$gdm3Resource.ori"
 
 # Restore backup function.
 restore () {
-mv "$gdm3Resource~" "$gdm3Resource"
+mv "$gdm3Resource.ori" "$gdm3Resource"
 if [ "$?" -eq 0 ]; then
     chmod 644 "$gdm3Resource"
     echo 'GDM background sucessfully restored.'
-    read -p 'Do you want to restart gdm to apply change? (y/n):' -n 1
-	echo
-	if [[ "$REPLY" =~ ^[yY]$ ]]; then
-	    service gdm restart
-	else
-	    echo 'Restart GDM service to apply change.'
-	    exit 0
-	fi
+    echo 'Restart GDM service to apply change.'
 fi
 }
 
@@ -67,7 +44,7 @@ workDir="/tmp/gdm3-theme"
 
 # Create directories from resource list.
 CreateDirs() {
-for resource in `gresource list "$gdm3Resource~"`; do
+for resource in `gresource list "$gdm3Resource.ori"`; do
     resource="${resource#\/org\/gnome\/shell\/}"
     if [ ! -d "$workDir"/"${resource%/*}" ]; then
       mkdir -p "$workDir"/"${resource%/*}"
@@ -77,8 +54,8 @@ done
 
 # Extract resources from binary file.
 ExtractRes() {
-for resource in `gresource list "$gdm3Resource~"`; do
-    gresource extract "$gdm3Resource~" "$resource" > \
+for resource in `gresource list "$gdm3Resource.ori"`; do
+    gresource extract "$gdm3Resource.ori" "$resource" > \
     "$workDir"/"${resource#\/org\/gnome\/shell\/}"
 done
 }
@@ -138,8 +115,9 @@ if [[ $(file --mime-type -b "$1") == image/*g ]]; then
 
     # Change gdm background to the image you submited.
     oldBg="#lockDialogGroup \{.*?\}"
-    newBg="#lockDialogGroup {
-	background: url('resource:\/\/\/org\/gnome\/shell\/theme\/$imgFile');
+    newBg=".login-dialog,
+ #lockDialogGroup {
+	background-image: url('resource:\/\/\/org\/gnome\/shell\/theme\/$imgFile');
 	background-size: cover; }"
     perl -i -0777 -pe "s/$oldBg/$newBg/s" "$workDir"/theme/gdm3.css
 
@@ -147,7 +125,7 @@ if [[ $(file --mime-type -b "$1") == image/*g ]]; then
     echo '<?xml version="1.0" encoding="UTF-8"?>
 <gresources>
     <gresource prefix="/org/gnome/shell/theme">' > "$workDir"/theme/"$gdm3xml"
-    for file in `gresource list "$gdm3Resource~"`; do
+    for file in `gresource list "$gdm3Resource.ori"`; do
 	echo "        <file>${file#\/org\/gnome/shell\/theme\/}</file>" \
 	>> "$workDir"/theme/"$gdm3xml"
     done
@@ -178,7 +156,8 @@ elif [[ "$1" =~ ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$ ]]; then
 
     # Change gdm background to the color you submited.
     oldBg="#lockDialogGroup \{.*?\}"
-    newBg="#lockDialogGroup {
+    newBg=".login-dialog,
+ #lockDialogGroup {
 	background: $BgColor;
 	background-size: cover; }"
     perl -i -0777 -pe "s/$oldBg/$newBg/s" "$workDir"/theme/gdm3.css
@@ -187,7 +166,7 @@ elif [[ "$1" =~ ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$ ]]; then
     echo '<?xml version="1.0" encoding="UTF-8"?>
 <gresources>
     <gresource prefix="/org/gnome/shell/theme">' > "$workDir"/theme/"$gdm3xml"
-    for file in `gresource list "$gdm3Resource~"`; do
+    for file in `gresource list "$gdm3Resource.ori"`; do
 	echo "        <file>${file#\/org\/gnome/shell\/theme\/}</file>" \
 	>> "$workDir"/theme/"$gdm3xml"
     done
@@ -209,7 +188,7 @@ else
     # show this message.
     echo 'Image file not found or wrong color hex code.'
     echo 'Please, submit a .jpg or .png image file or a valid hex code.'
-    echo 'Usage: sudo ./ubuntu-20.04-change-gdm-background /path/to/image.*g'
-    echo 'Usage: sudo ./ubuntu-20.04-change-gdm-background \#yourhexcode'
+    echo 'Usage: sudo ./change-gdm-background /path/to/image.*g'
+    echo 'Usage: sudo ./change-gdm-background \#yourhexcode'
 
 fi
